package(default_visibility = ["//visibility:public"])

cc_library(
    name = "net_address",
    srcs = [
        "ip_v4.cc",
        "ip_v6.cc",
    ],
    hdrs=[
        "ip_v4.h",
        "ip_v6.h",
        "net_address.h",
    ]
)
